[phases.setup]
runtime = "python311"
install = """
  python -m venv --copies /opt/venv &&
  . /opt/venv/bin/activate &&
  pip install -r requirements.txt
"""

[phases.build]
build = """
  . /opt/venv/bin/activate &&
  pip install -r requirements.txt
"""

[phases.start]
start = """
  . /opt/venv/bin/activate &&
  gunicorn django_proyect.wsgi:application
"""
