[phases.build]
cmds = [
  "pip install -r requirements.txt"
]

[phases.start]
cmd = "gunicorn django_proyect.wsgi:application --bind 0.0.0.0:$PORT"

[phases]
start = "gunicorn django_proyect.wsgi:application --bind 0.0.0.0:${PORT}"

